name: Backup Restore Test
on:
  workflow_dispatch:

jobs:
  restore-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install backend deps
        working-directory: zimmer-backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Start restore Postgres
        run: |
          docker compose -f ops/restore-compose.yml up -d postgres-restore
          for i in {1..30}; do
            docker inspect --format='{{json .State.Health.Status}}' zimmer_postgres_restore 2>/dev/null | grep -q healthy && break || sleep 1
          done
      
      - name: RUN: (Example) validate empty restored DB schema
        env:
          DATABASE_URL: postgresql+psycopg2://zimmer:zimmer@localhost:5433/zimmer_restore
        working-directory: zimmer-backend
        run: |
          alembic -c alembic.ini upgrade head
          python scripts/validate_constraints.py
          # NOTE: For real CI restore, you'd need to fetch a backup artifact from secure storage.
